services:
  - type: web
    name: coshop-backend
    env: java
    rootDir: backend
    autoDeploy: true
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: "21"
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        sync: false
      - key: APP_EXTENSION_API_KEY
        sync: false
      - key: APP_CORS_ALLOWED_ORIGIN_PATTERNS
        sync: false
